config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'schedule', to: 'schedules#index'
  get 'schedule_detail', to: 'schedules#show'
  post 'schedule_create', to: 'schedules#create'
  get 'schedule_edit/:id', to: 'schedules#edit'
  put 'schedule_update/:id', to: 'schedules#update'
  delete 'schedule_destroy/:id', to: 'schedules#destroy'
  get 'timeline', to: 'timelines#index'
  get 'evaluate', to: 'evaluates#index'
  get 'check_daily_schedule', to: 'schedule_results#index'
  post 'create_schedule_result', to: 'schedule_results#create'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create]
end

app/models/achievement_result.rb
class AchievementResult < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_action.rb
class DailyAction < ApplicationRecord
  belongs_to :user
  belongs_to :daily_evaluate
end

app/models/daily_evaluate.rb
class DailyEvaluate < ApplicationRecord

  has_many :daily_actions
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  has_one :schedule_result
end

app/models/schedule_result.rb
class ScheduleResult < ApplicationRecord
  belongs_to :schedule
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :daily_actions

  has_many :schedules
  has_many :achievement_results
end

# example_1@gmail.com
# password

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end

  def prepare_current_user
    @user = User.find(session[:user_id])
  end
end

app/controllers/evaluates_controller.rb
class EvaluatesController < ApplicationController
  before_action :prepare_current_user, only: %i[index]

  def index
    @weekly_achievement_rate = @user.achievement_results.where(duration: 'weekly').last&.achievement_rate
    @monthly_achievement_rate = @user.achievement_results.where(duration: 'monthly').last&.achievement_rate
    @totaly_achievement_rate = @user.achievement_results.where(duration: 'totaly').last&.achievement_rate
  end
end

app/controllers/schedule_results_controller.rb
class ScheduleResultsController < ApplicationController
  def index
    user_id = params[:user_id]
    yesterday = Time.zone.yesterday
    user = User.find(user_id)
    @target_schedules = user.schedules.where('start >= ?', yesterday.strftime("%F 00:00:00")).where('start < ?', yesterday.strftime("%F 24:00:00"))
    if @target_schedules.any? { |ts| ts.schedule_result.present? }
      redirect_to root_path
    else
      @schedule_result = ScheduleResult.new
    end
  end

  def create
    values = params[:results].values
    results = values.each_with_object([]) do |val, result|
      result << ScheduleResult.new(schedule_id: val['schedule_id'],
                                   is_success: val['is_success'],
                                   date: Time.zone.yesterday)
    end
    ScheduleResult.import results
    redirect_to root_path
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :require_user_logged_in
  before_action :prepare_current_user, only: %i[index show]

  def index
    @user_schedules = @user.schedules.map { |s| { title: s.title, start: s.start.strftime('%F') } }
    @schedule = Schedule.new
  end

  def show
    @date = params[:date].to_date
    @prev_date = @date - 1.days
    @next_date = @date + 1.days

    # 対象ユーザのある1日のスケジュールを全て取得
    user_daily_schedules = Schedule
                             .where(user_id: @user.id)
                             .where('start >= ?', @date.strftime("%F 00:00:00"))
                             .where('start < ?', @date.strftime("%F 24:00:00"))
    # 空の配列を用意
    @schedules = []
    # 複数あるスケジュールを1時間刻みで仕分ける
    (0..23).each do |t|
      # 開始時間tの条件に当てはまるスケジュールを変数target_schedulesに格納する
      target_schedules = user_daily_schedules
                           .where('start >= ?', @date.strftime("%F #{sprintf("%02d", t)}:00:00"))
                           .where('start < ?', @date.strftime("%F #{sprintf("%02d", t + 1)}:00:00"))
      # target_schedulesと@schedulesの同じ開始時間にそれぞれスケジュールをpushする
      @schedules.push({ start: "#{sprintf("%02d", t)}:00",
                        end: "#{sprintf("%02d", t + 1)}:00",
                        schedules: target_schedules})
    end
  end

  def edit
    @schedule = Schedule.find(params[:id])
    @date = params[:date]
  end

  def create
    @schedule = Schedule.new(schedule_params)
    @schedule.save
    redirect_to schedule_path
  end

  def update
    @schedule = Schedule.find(params[:id])
    @schedule.update(schedule_params)
    redirect_to schedule_path
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to schedule_path
  end

  private
# スケジュール新規作成時 ActionController::ParameterMissing (param is missing or the value is empty: schedule):エラーになる
  def schedule_params
    params.require(:schedule).permit(:title, :start, :end, :body, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  before_action :require_user_logged_in

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]

  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/evaluates/index.html.erb
<h1>ここ１週間の達成率</h1>
<p><%= @weekly_achievement_rate.presence || 0 %>%</p>
<h1>ここ１ヶ月の達成率</h1>
<p><%= @monthly_achievement_rate.presence || 0 %>%</p>
<h1>通算の達成率</h1>
<p><%= @totaly_achievement_rate.presence || 0 %>%</p>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark" style="background-color:#74992e;">
    <a class="navbar-brand" href="/">Qolc</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to user_path(current_user), class: 'nav-link' do %>
              <i class="fas fa-user"></i>
              <%= current_user.name %>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link" data-toggle="dropdown"><i class="fas fa-cog"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'タイムライン', timeline_path %></li>
              <li class="dropdown-item"><%= link_to 'スケジュールを見る', schedule_path %></li>
              <li class="dropdown-item"><%= link_to '自分の評価を見る', evaluate_path %></li>
            </ul>
          </li>
          <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class:'nav-link' %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'サインアップ', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qolc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <link href='https://cdn.jsdelivr.net/npm/fullcalendar@5.5.1/main.css' rel='stylesheet' />
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.5.1/main.min.js'></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= yield :head %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Qolc</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="#" class="nav-link">Signup</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Login</a></li>
      </ul>
    </div>
  </nav>
</header>

app/views/schedule_results/index.html.erb
<h1><%= Time.zone.yesterday.strftime("%Y年%m月%d日") %> のスケジュール</h1>

<%= form_with url: create_schedule_result_path do |f| %>
  <table class="table table-striped table-bordered">
    <tbody>
      <% @target_schedules.each_with_index do |ts, index| %>
        <tr class="row">
          <th class="col-2 text-center">
            <%= ts.start.strftime("%H:%M") %> ~ <%= ts.end.strftime("%H:%M") %>
          </th>
          <td class="col-7 text-center">
            <%= ts.title %>
          </td>
          <td class="col-3 text-center">
            <%= f.radio_button :is_success, :true, name: "results[#{index}][is_success]", checked: true %>
            <%= f.label :is_success, "できた" %>
            <%= f.radio_button :is_success, :false, name: "results[#{index}][is_success]" %>
            <%= f.label :is_success, "できなかった" %>
            <input class="d-none" name=<%= "results[#{index}][schedule_id]" %> value=<%= ts.id %>>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center">
    <%= f.submit "送信", class: "btn btn-success" %>
  <div>
<% end %>

app/views/schedules/edit.html.erb
<h3 class="text-center">スケジュール編集</h3>
<%= form_with model: @schedule, url: "/schedule_update/#{@schedule.id}", method: :put do |f| %>
  <div class="container">
    <div class="row">
      <label class="col-3">タイトル</label>
      <div class="col-9">
        <%= f.text_field :title, class: "form-control"%>
      </div>
      <label class="col-3">開始日時</label>
      <div class="col-9">
        <%= f.datetime_field  :start, class:"field" %>
      </div>
      <label class="col-3">終了日時</label>
      <div class="col-9">
        <%= f.datetime_field :end, class:"field" %>
      </div>
      <label class="col-3">詳細</label>
      <div class="col-9">
        <%= f.text_field :body, class: "form-control" %>
      </div>
      <%= f.hidden_field :user_id, :value => session[:user_id] %>
    </div>
    <div class="modal-footer">
      <%= f.submit "編集する", class: "btn btn-success" %>
      <button type="button" class="btn btn-default"><%= link_to '戻る', schedule_detail_path(date: @date), :style => "color:black" %></button>
    </div>
  </div>
<% end %>

app/views/schedules/index.html.erb
<div id="calendar"></div>

<button type="button" class="btn btn-primary mt-3" data-toggle="modal" data-target="#modal-schedule-create">
  スケジュール登録
</button>

<div id="modal-schedule-create" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">スケジュール登録</h4>
      </div>

      <div class="modal-body">
        <%= form_with model: @schedule, url: schedule_create_path do |f| %>
          <div class="container">
            <div class="row">
              <label class="col-3">タイトル</label>
              <div class="col-9">
                <%= f.text_field :title, class: "form-control", placeholder: "タイトルを入力してください" %>
              </div>
              <label class="col-3">開始日時</label>
              <div class="col-9">
                <%= f.datetime_field  :start, placeholder: "XXXX-XX-XX XX:XX", class:"field" %>
              </div>
              <label class="col-3">終了日時</label>
              <div class="col-9">
                <%= f.datetime_field :end, placeholder: "XXXX-XX-XX XX:XX", class:"field" %>
              </div>
              <label class="col-3">詳細</label>
              <div class="col-9">
                <%= f.text_field :body, class: "form-control", placeholder: "タイトルの詳細を記入してください" %>
              </div>
              <%= f.hidden_field :user_id, :value => session[:user_id] %>
            </div>
            <div class="modal-footer">
              <%= f.submit "登録する", class: "btn btn-success" %>
              <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
  var calendarEl = document.getElementById('calendar')
  var calendar = new FullCalendar.Calendar(calendarEl, {
    headerToolbar: {
      left: 'prev today',
      center: 'title',
      right: 'next'
    },
    navLinks: false,
    businessHours: true,
    editable: true,
    locale: 'ja',
    dateClick: function(info) {
      info.jsEvent.preventDefault(); // don't let the browser navigate
      window.location.href = '/schedule_detail?date=' + info.dateStr;
    }
  });
  calendar.render()
</script>

app/views/schedules/show.html.erb
<div class="row justify-content-between">
  <h5 class="col-1"><%= link_to '<戻る', schedule_path, :style => "color:black" %></h5>
  <h5 class="col-2"><%= link_to "<#{@prev_date}", schedule_detail_path(date: "#{@prev_date}"), :style => "color:black" %></h5>
  <h3 class="offset-2 col-3"><%= @date %></h3>
  <h5 class="offset-2 col-2"><%= link_to "#{@next_date}>", schedule_detail_path(date: "#{@next_date}"), :style => "color:black" %></h5>
</div>

<table class="table table-striped table-bordered">
  <tbody>
    <% @schedules.each do |schedule| %>
      <tr class="row">
        <th class="col-1 text-center"><%= schedule[:start] %></th>
        <td class="col-11 text-center">
        <% schedule[:schedules].each do |s|%>
          <%= link_to s.title, "#modal-schedule-show-#{s.id}", "data-toggle" => "modal", :style => "color:black" %>
          <div id="<%= "modal-schedule-show-#{s.id}" %>" class="modal fade" tabindex="-1">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title">スケジュール詳細</h4>
                </div>
                <div class="modal-body">
                  <div class="container">
                    <div class="row">
                      <%# id=1のスケジュールが表示されてしまう OK %>
                      <div class="col-3">タイトル</div>
                      <div class="col-9"><%= s.title %></div>
                      <div class="col-3">開始日時</div>
                      <div class="col-9"><%= s.start.strftime("%F %H:%M") %></div>
                      <div class="col-3">終了日時</div>
                      <div class="col-9"><%= s.end.strftime("%F %H:%M") %></div>
                      <div class="col-3">詳細</div>
                      <div class="col-9"><%= s.body %></div>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                <%# ボタンの反応範囲を広げたい %>
                  <button type="button" class="btn btn-success"><%= link_to "編集する", "/schedule_edit/#{s.id}?date=#{@date}", :style => "color:white"%></button>
                  <button type="button" class="btn btn-danger"><%= link_to "削除する", "/schedule_destroy/#{s.id}", :style => "color:white", method: :delete, data: { confirm: "本当に削除しますか？" } %></button>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="main">
    <div class="slider">
      <ul class="slider__container">
        <div id="photo1" class="slider__item slider__item1"><p class="bg-wrapper">質の高い生活は、<br>食事・運動・睡眠の３つを大切にすることです。</p></div>
        <div id="photo2" class="slider__item slider__item1"><p class="bg-wrapper">適度な運動は血行を良くします！<br>さぁ！汗をかこう！</p></div>
        <div id="photo3" class="slider__item slider__item1"><p class="bg-wrapper">朝食を甘く見てはいけません。<br>一日の生活を支える架け橋です！</p></div>
        <div id="photo4" class="slider__item slider__item1"><p class="bg-wrapper">睡眠不足はパフォーマンスが大きく低下します。<br>十分な睡眠時間の確保を意識しよう</p></div>
      </ul>
    </div>
    <% content_for :head do %>
      <%= stylesheet_link_tag "style.css" %>
    <% end %>

    <%= javascript_include_tag "slide.js" %>
</div>

  <div class="container">
    <div class="row">
      <div class="col-lg-4 mt-3">
        <h5 class="text-center">スケジュール</h5>
        <div class="box">
          <%= link_to schedule_path do %>
            <div class="sample">
              <%= image_tag "schedule.jpeg", :size =>'348x400' %>
              <div class="mask">
                <div class="caption">スケジュールを決める</div>
              </div>
            </div>
          <% end %>
        </div>
        <p class="text-center">まずはここで1日の予定や今後の予定を書き出そう！</p>
      </div>
      <div class="col-lg-4 mt-3">
        <h5 class="text-center">評価</h5>
        <div class="box">
          <%= link_to evaluate_path do %>
            <div class="sample">
              <%= image_tag "evaluate.jpeg", :size =>'348x400' %>
              <div class="mask">
                <div class="caption">自分の評価を見る</div>
              </div>
            </div>
          <% end %>
        </div>
        <p class="text-center">昨日の実績や過去の評価が見れます。</p>
      </div>
      <div class="col-lg-4 mt-3">
        <h5 class="text-center">実績の記入</h5>
        <div class="box">
          <%= link_to check_daily_schedule_path(user_id: session[:user_id]) do %>
            <div class="sample">
              <%= image_tag "timeline.jpeg", :size =>'348x400' %>
              <div class="mask">
                <div class="caption">１日の行動を振り返る</div>
              </div>
            </div>
          <% end %>
        </div>
        <p class="text-center">１日の行動をチェックすることができます。</p>
      </div>
    </div>
    <% content_for :head do %>
      <%= stylesheet_link_tag "solid.css" %>
    <% end %>
  </div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Microposts</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-success' %>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="#" class="nav-link">Microposts</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Followings</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Followers</a></li>
    </ul>
  </div>
</div>